spring:
  application:
    name: Amang_Web_BE
  profiles:
    include: secret
  datasource:
    url: jdbc:mysql://localhost:3306/amang_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: wjdgh01!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # (create, create-drop, update, validate 중 선택)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.back: DEBUG